export const STRINGS = {
  COMMON: {
    LOADING: "Memuat...",
    CLOSE: "Tutup",
    SEARCH_PLACEHOLDER: "Cari nama, bank, atau nominal",
    SORT: "URUTKAN",
    ERROR_TITLE: "Terjadi kesalahan",
    COPY_SUCCESS: "Disalin",
    UNKNOWN_ERROR: "Unknown error",
    NOT_FOUND: "Tidak ditemukan",
    TRY_AGAIN: "Silahkan coba lagi",
  },
  TRANSACTION_DETAIL: {
    TITLE: "DETAIL TRANSAKSI",
    ID_PREFIX: "ID TRANSAKSI: #",
    COPY_CONFIRMATION: "ID Transaksi telah disalin",
    TRANSFER_TITLE: "BERITA TRANSFER",
    UNIQUE_CODE: "KODE UNIK",
    AMOUNT: "NOMINAL",
    CREATED_TIME: "WAKTU DIBUAT",
  },
  TRANSACTION_LIST: {
    TITLE: "Transaction List",
    EMPTY_TITLE: (query: string) => `Kami tidak bisa menemukan "${query}"`,
    EMPTY_SUBTITLE:
      "Mohon cek lagi ejaannya atau ganti dengan nama, bank, atau nominal lain.",
  },
  SORT_OPTIONS: {
    DEFAULT: "URUTKAN",
    NAME_ASC: "Nama A-Z",
    NAME_DESC: "Nama Z-A",
    DATE_ASC: "Tanggal Terlama",
    DATE_DESC: "Tanggal Terbaru",
  },
  ERROR_MESSAGES: {
    TRANSACTION_NOT_FOUND: "Transaksi tidak ditemukan",
    DATE_INPUT_ERROR: "Input harus berupa string tanggal",
    DATE_INVALID: "Format tanggal tidak valid",
    MONTH_INDEX_OUT_OF_RANGE: "Indeks bulan di luar jangkauan",
  },
  MONTH: {
    JANUARY: "Januari",
    FEBRUARY: "Februari",
    MARCH: "Maret",
    APRIL: "April",
    MAY: "Mei",
    JUNE: "Juni",
    JULY: "Juli",
    AUGUST: "Agustus",
    SEPTEMBER: "September",
    OCTOBER: "Oktober",
    NOVEMBER: "November",
    DECEMBER: "Desember",
  },
  STATUS: {
    PENDING: "Pengecekan",
    PENDING_TEXT: "PENDING",
    SUCCESS: "Berhasil",
    SUCCESS_TEXT: "SUCCESS",
    FAILED: "Gagal",
    FAILED_TEXT: "FAILED",
  },
} as const;
